spring:
  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:h2:file:./tours/target/db/toursdb
    username: sa
    password:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


logging:
  level:
    jdbc: OFF
    jdbc.sqltiming: DEBUG


      

