CREATE TABLE If NOT EXISTS SPOTS(
    SPOT_ID INT PRIMARY KEY AUTO_INCREMENT,
    SPOT_NAME VARCHAR(50) NOT NULL,
    SPOT_LAT FLOAT NOT NULL,
    SPOT_LNG FLOAT NOT NULL,
);

CREATE TABLE IF NOT EXISTS users (
    user_name VARCHAR(100)  NOT NULL PRIMARY KEY,
    encoded_password VARCHAR(255)
);
