CREATE TABLE If NOT EXISTS SPOTS(
    SPOT_ID INT PRIMARY KEY,
    SPOT_NAME VARCHAR(50) NOT NULL,
    SPOT_LAT FLOAT NOT NULL,
    SPOT_LNG FLOAT NOT NULL,
    SPOT_NO INT NOT NULL,    
);

CREATE TABLE If NOT EXISTS TOURS(
    TOUR_ID INT PRIMARY KEY,
    TOUR_TITLE VARCHAR(50) NOT NULL,
    TOUR_DESCRIPTION VARCHAR(300),
);

CREATE TABLE If NOT EXISTS USERS (
    USERNAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
    ENCODED_PASSWORD VARCHAR_IGNORECASE(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
);

CREATE TABLE If NOT EXISTS AUTHORITIES (
    USERNAME  VARCHAR_IGNORECASE(50) NOT NULL,
    AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    CONSTRAINT UK_AUTHORITIES UNIQUE (USERNAME, AUTHORITY),
);

CREATE TABLE IF NOT EXISTS CONTENTS (
    CONTENT_ID INT PRIMARY KEY,
    CONTENT_TYPE INT NOT NULL,
    CONTENT_NO INT NOT NULL;
    CONTENT_DESCRIPTION VARCHAR(200), 
    CONTENT_DETAIL VARCHAR(21844) NOT NULL,
)